import Navigation from "./components/nav";
import type { Metadata } from "next";
import "./globals.css";


export const metadata: Metadata = {
  title: "Portafolio Anthony Barrantes",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Navigation/>
        <div className="container">{children}</div>
      </body>
    </html>
  );
}
